In [1]:
import nltk
from nltk.metrics import *
doc_1 = "Data is the new oil of the digital economy"
doc_2 = "Data is a new oil"
words_doc1=doc_1.lower().split()
words_doc1
words_doc2=doc_2.lower().split()
words_doc2
set_doc1=set(words_doc1)
set_doc2=set(words_doc2)
print(set_doc1)
intersection = set_doc1.intersection(set_doc2)
union = set_doc1.union(set_doc2)
jaccard=float(len(intersection)) / len(union)
jaccard

{'new', 'oil', 'of', 'the', 'is', 'data', 'economy', 'digital'}


0.4444444444444444

In [8]:
#LEVENSHTEIN DISTANCE

import enchant
data1= "shruti jain is a good girl."
data2 = "shruti jain" 
enchant.utils.levenshtein(data1,data2) 

16

In [9]:
#COSINE SIMILARITY
import nltk
nltk.download ( ' punkt ' )
nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize


I = input("Enter first string: ").lower() 
II = input("Enter second string: ").lower()


[nltk_data] Error loading  punkt : Package ' punkt ' not found in
[nltk_data]     index
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Shruti\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


Enter first string: shruti is a good girl
Enter second string: shruti studies at ncu


In [11]:
# tokenization
I_list = word_tokenize(I) 
II_list = word_tokenize(II) 
print('First List', I_list) 
print('Second Lzst', II_list)



First List ['shruti', 'is', 'a', 'good', 'girl']
Second Lzst ['shruti', 'studies', 'at', 'ncu']


In [14]:
#removing stopwords

sw = stopwords.words('english') 
l1 =[]
l2 =[]
I_set = {w for w in I_list if not w in sw}
II_set = {w for w in II_list if not w in sw}
 
print ( ' First Set ' ,I_set)
print ( ' second Set' ,II_set )
 



 First Set  {'shruti', 'good', 'girl'}
 second Set {'shruti', 'ncu', 'studies'}


In [24]:
# Forming a set containing keywords of both strings

rvector = I_set.union(II_set) 
for w in rvector:
    if w in I_set: 
        l1.append(1) 
    else: 
        l1.append(0)
    if w in II_set: 
        l2.append(1) 
    else: 
        l2.append(0)
c = 0


In [35]:
#Cosine similarity matrix
I = input("Enter first string: ").lower() 
II = input("Enter second string: ").lower()


Enter first string: shruti jain is the student of text and web analytics
Enter second string: shruti jain is the student of northcap university


In [58]:
documents = [I,II]
from sklearn.feature_extraction.text import CountVectorizer 
import pandas as pd
count_vectorizer = CountVectorizer(stop_words='english') 
count_vectorizer = CountVectorizer()
sparse_matrix = count_vectorizer.fit_transform(documents)
doc_term_matrix = sparse_matrix.todense() 
df = pd.DataFrame(doc_term_matrix,columns=count_vectorizer.get_feature_names(),index=['I', 'II'])
df


analytics  and  is  jain  northcap  of  shruti  student  text  the  \
I           1    1   1     1         0   1       1        1     1    1   
II          0    0   1     1         1   1       1        1     0    1   

    university  web  
I            0    1  
II           1    0

In [37]:
#2.Calculate the TF-IDF vectorizer on 2 documents.
#TF-IDF
import pandas as pd 
from sklearn.feature_extraction.text import CountVectorizer 
from sklearn.feature_extraction.text import TfidfVectorizer
text = ["Do not limit your challenges,challenge your limits",
        "your challenges",
        "their limits"]
vect = TfidfVectorizer()
X = vect.fit_transform(text)
print(vect.get_feature_names())
vect.idf_

['challenge', 'challenges', 'do', 'limit', 'limits', 'not', 'their', 'your']


array([1.69314718, 1.28768207, 1.69314718, 1.69314718, 1.28768207,
       1.69314718, 1.69314718, 1.28768207])

In [42]:
#3.Apply the max-df, min-df param in the TF-IDF function.
data= [I,II]
from sklearn.feature_extraction.text import CountVectorizer 
import pandas as pd
count_vec = CountVectorizer(stop_words='english',analyzer="word",ngram_range=(1,1),max_df=0.50,min_df=1,max_features=None) 
count_train= count_vec.fit(data)
bag_of_words=count_vec.transform(data)
print("features:",count_vec.get_feature_names())


features: ['analytics', 'northcap', 'text', 'university', 'web']


In [50]:
#4.Compute Cosine Similarity using both TF-IDF and Count vectorizer 
from sklearn.feature_extraction.text import CountVectorizer 
from sklearn.feature_extraction.text import TfidfTransformer
from nltk.corpus import stopwords
import numpy as np
import numpy.linalg as LA 
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Shruti\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [51]:
train_dataset=["shruti is a good girl","shruti studies at northcap university"]#document
test_dataset=["a good girl named shruti studies at nothcap university"]#query
stopWords=stopwords.words("English")

In [56]:
vectorizer = CountVectorizer(stop_words = stopWords) 
print('Vectorizer : ',vectorizer)
transformer = TfidfTransformer() 
print('\n\nTF-IDF Transformer : ',transformer)
#Using Count Vectorizer
trainVectorizerArray = vectorizer.fit_transform(train_dataset).toarray() 
testVectorizerArray =vectorizer.transform(test_dataset).toarray()
print ('Fit Vectorizer to train set \n', trainVectorizerArray)
print ('\n\nTransform Vectorizer to test set\n', testVectorizerArray)


Vectorizer :  CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None,
                stop_words=['i', 'me', 'my', 'myself', 'we', 'our', 'ours',
                            'ourselves', 'you', "you're", "you've", "you'll",
                            "you'd", 'your', 'yours', 'yourself', 'yourselves',
                            'he', 'him', 'his', 'himself', 'she', "she's",
                            'her', 'hers', 'herself', 'it', "it's", 'its',
                            'itself', ...],
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)


TF-IDF Transformer :  TfidfTransformer(norm='l2', smooth_idf=True, sublinear_tf=False, use_idf=True)
Fit Vectorizer to train set 
 [[1 1 0 1 0 0]
 [0 0 1 1 1 

In [57]:
 #Using 
transformer.fit(trainVectorizerArray)
print('Fit transformer to train set \n',transformer.transform(trainVectorizerArray).toarray()) 
transformer.fit(testVectorizerArray)
tfidf = transformer.transform(testVectorizerArray) 
print('\n\nFit transformer to test set\n',tfidf.todense())


Fit transformer to train set 
 [[0.6316672  0.6316672  0.         0.44943642 0.         0.        ]
 [0.         0.         0.53404633 0.37997836 0.53404633 0.53404633]]


Fit transformer to test set
 [[0.4472136 0.4472136 0.        0.4472136 0.4472136 0.4472136]]
